### ISSUE TITLE
When using SwapChainPanel via SkiaSharp in .NET MAUI 9.0 Preview on Windows, WinRT throws an exception after a while

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [microsoft/CsWinRT#1641]
**Description**

We are using SkiaSharp 3.0 Preview 3.1 in .NET MAUI 9.0 Preview 5 and .NET 9.0 Preview 5 SDK in our GnollHack game. It is using WinUI 3 as a backend target. SkiaSharp's SKGLView on WinUI 3 uses SwapChainPanel, which works for a while but then throws a WinRT-related exception:

```
System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()

   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in C:\Users\TommiGustafsson\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 44
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() in C:\Users\TommiGustafsson\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 30
   at .cctor()
```

**To Reproduce**
1. Compile .NET MAUI Windows port using these instructions:
https://github.com/hyvanmielenpelit/GnollHack/wiki/Development-Information
(It's a relatively big task, I warn you.)

2. Start the game and enable GPU acceleration in the settings. Play the game for a while until it crashes. 10 minutes is usually enough.

**Expected behavior**
The game would not crash

**Version Info**
- .NET MAUI 9.0 Preview 5
- .NET SDK 9.0 Preview 5
- SkiaSharp 3.0 Preview 3.1

**Additional context**
Event Log entry:
```
Name:      Application
Source:        .NET Runtime
Date:          13.6.2024 23.03.41
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ProArt
Description:
Application: GnollHackM.exe
CoreCLR Version: 9.0.24.30607
.NET Version: 9.0.0-preview.5.24306.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()

   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in C:\Users\TommiGustafsson\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 44
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() in C:\Users\TommiGustafsson\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 30
   at .cctor()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-06-13T20:03:41.0292988Z" />
    <EventRecordID>62152</EventRecordID>
    <Correlation />
    <Execution ProcessID="33396" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ProArt</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: GnollHackM.exe
CoreCLR Version: 9.0.24.30607
.NET Version: 9.0.0-preview.5.24306.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---&gt; System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()

   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in C:\Users\TommiGustafsson\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 44
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() in C:\Users\TommiGustafsson\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\include\DeploymentManagerAutoInitializer.cs:line 30
   at .cctor()
</Data>
  </EventData>
</Event>
```

**Comment by dongle-the-gadget** [comment]
You're running unpackaged right? Does it happen if you use it packaged?

**Comment by TommiGustafsson-HMP** [comment]
I asked MAUI guys and they told me that a debug mode app in MAUI is packaged but also a weird hybrid because of the way how it registers itself.

**Comment by dongle-the-gadget** [comment]
Looking at it, it seems like Windows App SDK is just unloading itself from your app, which shouldn't happen in packaged mode, since packaged mode would force Windows App SDK to be loaded with your app at all times.

**Comment by TommiGustafsson-HMP** [comment]
There's also a related error, which I posted here:
https://github.com/microsoft/microsoft-ui-xaml/issues/9736
