### ISSUE TITLE
CsWinRT 2.1.1 breaks the application which works on 2.0.8

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/CsWinRT#1713]
**Describe the bug**
I'm using WAP project to pack my application base on latest Windows App SDK and there are two projects which is background CsWinRT task. I update the CsWinRT to 2.1.1 and no code changes, it just crash on startup. Rolling back to 2.0.8 fixed that issue.

Exception:
    - Type: System.Reflection.TargetInvocationException
    - Message: Exception has been thrown by the target of an invocation.

InnerException 1:
    - Type: Exception has been thrown by the target of an invocation.
    - Message: Exception has been thrown by the target of an invocation.

InnerException 2:
    - Type: Managed vtable types (ie. containing any reference types) are not supported.
    - Message: Managed vtable types (ie. containing any reference types) are not supported.

StackTrace:
```
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at WinRT.IWinRTObject.<IsInterfaceImplementedFallback>g__GetObjectReferenceViaVftbl|1_1(IObjectReference objRef, Type vftblType)
   at WinRT.IWinRTObject.IsInterfaceImplementedFallback(RuntimeTypeHandle interfaceType, Boolean throwIfNotImplemented)
   at WinRT.IWinRTObject.System.Runtime.InteropServices.IDynamicInterfaceCastable.IsInterfaceImplemented(RuntimeTypeHandle interfaceType, Boolean throwIfNotImplemented)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
   at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
   at WinRT.MarshalInterface`1.FromAbi(IntPtr ptr)
   at ABI.Windows.Storage.IStorageFileStaticsMethods.GetFileFromApplicationUriAsync(IObjectReference _obj, Uri uri)
   at Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(Uri uri)
```

**To Reproduce**
As above.

**Expected behavior**
Do not throw any exception

**Version Info**
.Net SDK 8.0.7
CsWinRT 2.1.1
Windows App SDK: 1.5.240627000

**Additional context**
None

**Comment by dongle-the-gadget** [comment]
You most likely need updated projections.

**Comment by zhuxb711** [comment]
> You most likely need updated projections.

Could share more details about "updated projections"? Thanks.

**Comment by manodasanW** [comment]
You will likely need the updated Windows SDK projection.  You can get that by adding the below property.  It will also be in upcoming .NET SDK builds.  Once it is available there, you can remove the below workaround.

If you are on .NET 6:

```<WindowsSdkPackageVersion>10.0.<target_os_version>.38</WindowsSdkPackageVersion>```

If you are on .NET 8:

```<WindowsSdkPackageVersion>10.0.<target_os_version>.39</WindowsSdkPackageVersion>>```

Replace <target_os_version> with the OS version in your target framework.

**Comment by manodasanW** [comment]
Let me know if you still run into this with the updated Windows SDK projection being used via `WindowsSdkPackageVersion`.  The updated versions are also now in the upcoming .NET SDK servicing build so explicitly specifying it will only be needed until that is out.

**Comment by zhuxb711** [comment]
Thanks~ Add this line in the csproj helps that.
`<WindowsSdkPackageVersion>10.0.22621.42</WindowsSdkPackageVersion>`
