### ISSUE TITLE
Investigate AddPackageAsync hangs

### ISSUE THREAD

**Issue by manodasanW** [microsoft/CsWinRT#1720]
Determine whether issue still repros with recent version and investigate:

https://github.com/dotnet/wpf/issues/4097

**Comment by ekalchev** [comment]
This is easily reproducible. Just create an empty WPF app and call

await packageManager.AddPackageAsync(...)

it is not reproduced every time but usually on every 5 calls, hangs at least 1 time

Calling the method synchrously packageManager.AddPackageAsync(...).GetWaiter().GetResult()
is a workaround but we notice the installation of the same package is noticeable slower.

**Comment by ekalchev** [comment]
We found that calling `packageManager.AddPackageAsync(...).GetWaiter().GetResult()`
from net48 application also causes deadlock. 

The deadlocks are reproduced ONLY with Release builds

**Comment by dongle-the-gadget** [comment]
net48 has a different WinRT runtime, not CsWinRT.

**Comment by ekalchev** [comment]
> net48 has a different WinRT runtime, not CsWinRT.

We are able to reproduce the deadlock with both .net8.0 and net48

**Comment by ekalchev** [comment]
We found that if we turn off optimization in Release it works.

```XML
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <Optimize>False</Optimize>
</PropertyGroup>
```

**Comment by manodasanW** [comment]
@ekalchev Are you using CsWinRT projections in net48 or are you using the built-in support?

**Comment by ekalchev** [comment]
We are using this nuget version https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts

If you can't reproduce it, we can provide a code that reproduce it.

**Comment by krasidachev** [comment]
Would be great to have some progress here - same issue with my project!

**Comment by ekalchev** [comment]
We have identified additional details regarding this issue. By passing a CancellationToken to the affected methods, the freezing problem is resolved. Here is an example of how to implement this:

```CSharp
using(CancellationTokenSource cts = new CancellationTokenSource ())
{
await packageManager.StagePackageAsync(uri, null).AsTask(cts .Token)
}
```

Using this approach, we conducted thousands of package installations with AddPackageAsync and StagePackageAsync, and none of these operations froze, unlike when they were executed without a CancellationToken. We hope this information helps in addressing the issue or provides a viable workaround.

**Comment by Aetopia** [comment]
> We have identified additional details regarding this issue. By passing a CancellationToken to the affected methods, the freezing problem is resolved. Here is an example of how to implement this:
> 
> using(CancellationTokenSource cts = new CancellationTokenSource ())
> {
> await packageManager.StagePackageAsync(uri, null).AsTask(cts .Token)
> }
> 
> Using this approach, we conducted thousands of package installations with AddPackageAsync and StagePackageAsync, and none of these operations froze, unlike when they were executed without a CancellationToken. We hope this information helps in addressing the issue or provides a viable workaround.

Does the workaround still work if `CancellationToken.None` is passed around?

**Comment by ekalchev** [comment]
Yes

**Comment by Nevca** [comment]
I have also stumbled upon the same issue and it is very annoying. I would love to see this being worked on.

**Comment by ekalchev** [comment]
> > We have identified additional details regarding this issue. By passing a CancellationToken to the affected methods, the freezing problem is resolved. Here is an example of how to implement this:
> > using(CancellationTokenSource cts = new CancellationTokenSource ())
> > {
> > await packageManager.StagePackageAsync(uri, null).AsTask(cts .Token)
> > }
> > Using this approach, we conducted thousands of package installations with AddPackageAsync and StagePackageAsync, and none of these operations froze, unlike when they were executed without a CancellationToken. We hope this information helps in addressing the issue or provides a viable workaround.
> 
> Does the workaround still work if `CancellationToken.None` is passed around?

Actually, we found another PackageManager method hangs `AddPackageByAppInstallerFileAsync`. We tried with to call AsTask with `new CancelationToken` and `CancellationToken.None` but it the problem still was present.

The workaround with the cancellationToken works only if it is constructed by CancellationTokenSource like that.

```CSharp
using(CancellationTokenSource cts = new CancellationTokenSource ())
{
await packageManager.AddPackageByAppInstallerFileAsync(uri, null).AsTask(cts .Token)
}
```

**Comment by yordans** [comment]
I'm encountering the same problem. Could you please resolve it?

**Comment by nssimeonov** [comment]
It is really frustrating that such an issue hasn't been addressed yet, especially since it only occurs in Release and not consistently. This behavior is extremely inconvenient and disruptive to the workflow. Why is this problem still unresolved? It's clearly an important issue, and it’s time it was properly addressed.

I'm encountering the same issue as well, so I kindly ask for it to be resolved.

**Comment by whiskhub** [comment]
This is still an issue, and for me even in a WinUI 3 app.

**Comment by ekalchev** [comment]
It’s concerning that this issue has persisted for years without an official response from Microsoft. The API is currently not functioning as expected, and we would appreciate timely communication and a resolution from the Microsoft team.

**Comment by Aetopia** [comment]
It seems the issue is with [`WindowsRuntimeSystemExtensions.AsTask()`](https://learn.microsoft.com/en-us/dotnet/api/system.windowsruntimesystemextensions) or specifically with how it wraps asynchronous Windows Runtime operations & awaits them.

That makes me ask has anyone tried to wrap asynchronous Windows Runtime operations themselves using `TaskCompletionSource<T>`/`TaskCompletionSource` & see if the issue still occurs? Because if it does then something is clearly wrong with ` WindowsRuntimeSystemExtensions.AsTask()`.

Here an implementation for wrapping `IAsyncOperationWithProgress<TResult, TProgress>` as `Task<TResult> which supports:

- Attaching a handler for progress via callbacks.

- Ability to cancel the asynchronous operation by passing a cancellation token.

- Handler error propagation to underlying wrapping task.

```csharp
public static async Task<TResult> Task<TResult, TProgress>(
    this IAsyncOperationWithProgress<TResult, TProgress> info,
    AsyncOperationProgressHandler<TResult, TProgress> handler = default,
    CancellationToken token = default
)
{
    // Check if the caller has passed a handler.

    bool flag = handler is not null;

    // Only asynchronously await if the operation hasn't completed.

    if (info.Status is AsyncStatus.Started)
    {
        TaskCompletionSource<object> source = new();

        // Propagate the errors from the caller's handler by wrapping it. 

        void Handler(IAsyncOperationWithProgress<TResult, TProgress> info, TProgress status)
        {
            try { handler(info, status); }
            catch (Exception exception) { source.TrySetException(exception); }
        }

        // Attach the handler only if the caller passed one.

        if (flag) info.Progress += Handler;

        info.Completed += (info, status) =>
        {
            // Detach the handler only if the caller passed one.

            if (flag) info.Progress -= Handler;
            source.TrySetResult(null);
        };

        using var registration = token.Register(info.Cancel);
        await source.Task.ConfigureAwait(false);
    }

    // Check if the operation was canceled, errored or completed.
        
    return info.Status switch
    {
        AsyncStatus.Error => throw info.ErrorCode,
        AsyncStatus.Canceled => throw new TaskCanceledException(),
        _ => info.GetResults(),
    };
}
```

Consuming the extension method that wraps the operation:

```csharp
var manager = new PackageManager();
using CancellationTokenSource source = new();

await manager.AddPackageAsync(new("https://www.example.com"), null, DeploymentOptions.None).Task((info, progress) =>
{
    Console.WriteLine($"{progress.state}, {progress.percentage}%");
}, source.Token);
```

Exception Stack Trace:

```
Unhandled Exception: System.Exception: Package could not be opened.

error 0x8007000D: Opening the package from location  failed.
   at Extensions.<Task>d__0`2.MoveNext() in ...
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Program.<Main>d__0.MoveNext() in ...
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Program.<Main>()
```

**Comment by ekalchev** [comment]
@Aetopia you are trying to install package from a invalid URL. "https://www.example.com"

**Comment by Aetopia** [comment]
> [@Aetopia](https://github.com/Aetopia) you are trying to install package from a invalid URL. "https://www.example.com"

I just wanted to demo the extension method wrapper in action in this case, it catching the erroe thrown by the operation.

**Comment by ekalchev** [comment]
The issue occurs only in Release builds and if there is no instance of CancellationToken passed and default is used ( or CancenllationToken.None), that suggest that the problem is somehow related to the generated IL by the compiler on probably we can't see it in C# code implementation.

**Comment by Aetopia** [comment]
> The issue occurs only in Release builds and if there is no instance of CancellationToken passed and default is used ( or CancenllationToken.None), that suggest that the problem is somehow related to the generated IL by the compiler on probably we can't see it in C# code implementation.

The runtime + compiler implicitly calls [WindowsRuntimeSystemExtensions.AsTask()](https://learn.microsoft.com/en-us/dotnet/api/system.windowsruntimesystemextensions) to wrap a async operation. hence you may try inspecting `System.Runtime.WindowsRuntime.dll` via ILSpy or your preferred decompiler.

**Comment by Aetopia** [comment]
> The issue occurs only in Release builds and if there is no instance of CancellationToken passed and default is used ( or CancenllationToken.None), that suggest that the problem is somehow related to the generated IL by the compiler on probably we can't see it in C# code implementation.

I tried wrapping `IAsyncOperationWithProgress<TResult, TProgress>` with `TaskCompletionSource` and the issue still occurs. So as you mentioned, the issue could be with the generated IL itself when awaiting the operation through `.AsTask()` & `TaskCompletionSource`.

Another potential solution would be to avoid `.AsTask()` & `TaskCompletionSource` provided by the runtime entirely and instead:

- Synchronously wait for the operation to finish by binding it to `ManualResetEventSlim`.

   - You could also use `CreateEvent()`, `SetEvent()` & `WaitForSingleObject` instead.
  
- Converting the synchronous task to an asynchronous task using `Task.Run()`.

This basically provides the required asynchrony through a "hacky" solution.

```csharp
public static async Task<TResult> ToTask<TResult, TProgress>(
    this IAsyncOperationWithProgress<TResult, TProgress> @this, 
    [Optional] CancellationToken token, 
    [Optional] AsyncOperationProgressHandler<TResult, TProgress> handler
)
{
    if (@this.Status is AsyncStatus.Started) await Task.Run(() =>
    {
        using ManualResetEventSlim @event = new();
        using var registration = token.Register(@this.Cancel);

        try
        {
            @this.Completed += (_, _) => @event.Set();
            if (handler is { }) @this.Progress += handler;
            @event.Wait();
        }
        finally { if (handler is { }) @this.Progress -= handler; }
    });

    return @this.Status switch
    {
        AsyncStatus.Completed => @this.GetResults(),
        AsyncStatus.Error => throw @this.ErrorCode,
        AsyncStatus.Canceled => throw new OperationCanceledException(),
        _ => throw new InvalidOperationException()
    };
}
```

Example:
```csharp
var operation = new PackageManager().AddPackageAsync(new Uri("https://example.com"), null, DeploymentOptions.None);

/*
    - Bind the async operation to the runtime provided `.AsTask`.
    - Bind the async operation the custom `.ToTask()`
*/

var runtime = operation.AsTask();
var custom = operation.ToTask();

/*
    Both awaits fail.
*/

try { await custom; }
catch { Console.WriteLine("The Custom Task failed!"); }

try { await runtime; }
catch { Console.WriteLine("The Runtime Task failed!"); }

/*
    Both return the same faulted result.
*/

Console.WriteLine($"Runtime: {runtime.IsFaulted}, Custom: {custom.IsFaulted}");
```
