### ISSUE TITLE
CsWinRT fails during code generation with NullReferenceException

### ISSUE THREAD

**Issue by ppoirier1** [microsoft/CsWinRT#1837]
**Describe the bug**
Build fails with the following during code generation: 
CSC : warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'.

**Version Info**
CsWinRT version 2.1.1 and higher
Windows SDK 22621

**Additional context**
Broke at 2.1.1. Version 2.0.8 and earlier versions worked fine.  Tried up to the current version 2.1.6
Log.txt:
...
output: C:\Users\user\AppData\Local\Temp\CsWinRT\q22y5fj2.4ha
time: 65ms

Adding C:\Users\user\AppData\Local\Temp\CsWinRT\q22y5fj2.4ha\AuthoringMetadataTypeMappingHelper.cs
Adding C:\Users\user\AppData\Local\Temp\CsWinRT\q22y5fj2.4ha\InitalizeProjection.cs
Adding C:\Users\user\AppData\Local\Temp\CsWinRT\q22y5fj2.4ha\Tasks.cs
Adding C:\Users\user\AppData\Local\Temp\CsWinRT\q22y5fj2.4ha\WinRTEventHelpers.cs
Adding C:\Users\user\AppData\Local\Temp\CsWinRT\q22y5fj2.4ha\WinRT_Module.cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at Generator.WinRTTypeWriter.<>c.<GenerateWinRTExposedClassAttributes>b__80_1(VtableAttribute vtableAttribute, Int32 _)
   at System.Linq.Enumerable.<SelectManyIterator>d__19`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Generator.WinRTTypeWriter.GenerateWinRTExposedClassAttributes(GeneratorExecutionContext context)
   at Generator.ComponentGenerator.Generate()

**Comment by manodasanW** [comment]
Fixed by null check added in WinRtTypeWriters for GetVtableAttributeToAddCall in #1861
