### ISSUE TITLE
Bug: Internal Speech Error (Windows.Media.SpeechRecognition)

### ISSUE THREAD

**Issue by PerfectlyFineCode** [microsoft/CsWinRT#1884]
### Description

When you initialize a new instance of `Windows.Media.SpeechRecognition.SpeechRecognizer` you will get this error
```
Unhandled exception. System.Runtime.InteropServices.COMException (0x800455A0): The text associated with this error code could not be found.

Internal Speech Error.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at WinRT.IActivationFactoryMethods.ActivateInstance[I](IObjectReference obj)
   at Windows.Media.SpeechRecognition.SpeechRecognizer..ctor()

```

Steps done:
Changed TargetFramework to `<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>`
Used both CsWinRT and changing csproj Sdk property to `Microsoft.NET.Sdk.WindowsDesktop` (not simultaneously)

### Steps To Reproduce

1. Create a WPF or Avalonia project.
2. Change TargetFramework to `net8.0-windows10.0.19041.0`
3. Install CsWinRT
4. Initialize a new instance of `Windows.Media.SpeechRecognition.SpeechRecognizer`
5. Crash with the same error

### Expected Behavior

It should not crash and successfully work.

### Version Info

CsWinRT Version: 2.2.0
.NET SDK: 8.0.400
Windows SDK: 10.0.19041.0

**Comment by PerfectlyFineCode** [comment]
Well, apparently this is a bug with running the program as administrator and seems to have nothing to do with CsWinRT but the flaky WinRT API Instead.
