### ISSUE TITLE
InvalidOperationException in casting for IBindableIterator

### ISSUE THREAD

**Issue by ujjwalchadha** [microsoft/CsWinRT#543]
Steps to repro:
1. Checkout the [manual projection testing branch ](https://github.com/microsoft/CsWinRT/tree/ujjwalchadha/test-manual-projections)
2. Build and run: UnitTest.TestCSharp.TestIBindableIterator

The test fails with:
```
 System.InvalidOperationException : Type 'ABI.Microsoft.UI.Xaml.Interop.IBindableIterator' returned by IDynamicInterfaceCastable does not implement the requested interface 'Microsoft.UI.Xaml.Interop.IBindableIterator'.
  Stack Trace:
     at Microsoft.UI.Xaml.Interop.IBindableIterator.MoveNext()
   at TestComponentCSharp.IBindableIteratorTest.MoveNext() in C:\Users\ujchadha\source\repos\CsWinRT\Projections\Test\Generated Files\net5.0\TestComponentCSharp.cs:line 971
   at UnitTest.TestCSharp.TestIBindableIterator() in C:\Users\ujchadha\source\repos\CsWinRT\UnitTest\TestComponentCSharp_Tests.cs:line 2160
```

**Comment by AdamBraden** [comment]
Confirm what happens with UWP/NETNative and confirm same behavior.

**Comment by AdamBraden** [comment]
The scenario does work in .NETNative, not clear that this is a real customer scenario

**Comment by AdamBraden** [comment]
Considered a test scearnio, leave in 1.2

**Comment by manodasanW** [comment]
While addressing #1303, I noticed the test this talks about is passing and was probably addressed during our previous collections refactor.
