### ISSUE TITLE
IMap.GetView() & IVector.GetView() call from native side on managed IDictionary & IList implementations respectively result in InvalidCastException

### ISSUE THREAD

**Issue by ujjwalchadha** [microsoft/CsWinRT#553]
Repro steps: 
1. Disable TestWinRT clone from git in build.cmd
2. In TestWinRT, in TestRunner.cpp, in function Collection3Call, add the following line to consume the managed IDictionary object's Do_Abi_GetView_ method:
```
TEST_REQUIRE_N(L"Collection", 3, c.GetView().Size() == 3);
```
3. Run build.cmd and check result for test: `UnitTest.TestWinRT.Collections_Dictionary_Call`

It fails with the following exception:
```
[xUnit.net 00:00:03.19]       System.InvalidCastException : Specified cast is not valid.
[xUnit.net 00:00:03.19]       Stack Trace:
[xUnit.net 00:00:03.20]            at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
[xUnit.net 00:00:03.20]         C:\Users\ujchadha\source\repos\CsWinRT\WinRT.Runtime\ObjectReference.cs(55,0): at WinRT.IObjectReference.As[T](Guid iid)
[xUnit.net 00:00:03.20]         C:\Users\ujchadha\source\repos\CsWinRT\WinRT.Runtime\ObjectReference.cs(51,0): at WinRT.IObjectReference.As[T]()
[xUnit.net 00:00:03.20]         C:\Users\ujchadha\source\repos\CsWinRT\WinRT.Runtime\Marshalers.cs(845,0): at WinRT.MarshalInterface`1.CreateMarshaler(T value)
[xUnit.net 00:00:03.20]         C:\Users\ujchadha\source\repos\CsWinRT\WinRT.Runtime\Marshalers.cs(861,0): at WinRT.MarshalInterface`1.FromManaged(T value)
[xUnit.net 00:00:03.20]         C:\Users\ujchadha\source\repos\CsWinRT\WinRT.Runtime\Projections\IDictionary.net5.cs(610,0): at ABI.System.Collections.Generic.IDictionary`2.Vftbl.Do_Abi_GetView_3(IntPtr thisPtr, IntPtr& __return_value__)
[xUnit.net 00:00:03.20]         --- End of stack trace from previous location ---
[xUnit.net 00:00:03.20]         C:\Users\ujchadha\source\repos\CsWinRT\WinRT.Runtime\ExceptionHelpers.cs(65,0): at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
[xUnit.net 00:00:03.20]         C:\Users\ujchadha\source\repos\CsWinRT\Projections\Test\Generated Files\net5.0\TestComponent.cs(8838,0): at ABI.TestComponent.ITests.global::TestComponent.ITests.Collection3Call(Collection3Handler handler)
[xUnit.net 00:00:03.20]         C:\Users\ujchadha\source\repos\CsWinRT\UnitTest\TestComponent_Tests.cs(677,0): at UnitTest.TestWinRT.Collections_Dictionary_Call()
```

**Comment by ujjwalchadha** [comment]
The same error occurs on IMapView.Split() call on a managed IReadOnlyDictionary object
