### ISSUE TITLE
WinRTTypeWriter.AddType NullReferenceException

### ISSUE THREAD

**Issue by vesuvian** [microsoft/CsWinRT#622]
- What versions of .NET, C#/WinRT, and the SDK Projection you're using
I've downloaded the current master CsWinRT commit (bd1fd97654be460e077cc8262de5038ab6a5c990)
`    <TargetFramework>net5.0</TargetFramework>`

- What tools and apps you're using (e.g. VS 2019, VSCode, etc.)
Visual Studio 2019

- What build of Windows your device is running
Windows 10 Pro

I first ran into this problem when using the CsWinRt Nuget package (1.1.0) to a brand new .Net Core Class Library (.Net 5.0) to generate a .winmd component. My Generated Files log.txt contains the following:

```
Generating assembly ICD.Profound.AppSwitcher.WinRT.Component version 1.0.0.0
attribute type found 
adding attribute type
System.NullReferenceException: Object reference not set to an instance of an object.
   at Generator.WinRTTypeWriter.AddType(INamedTypeSymbol type)
   at Generator.WinRTTypeWriter.AddCustomAttributes(String attributeTypeName, IList`1 primitiveTypes, IList`1 primitiveValues, EntityHandle parentHandle)
   at Generator.WinRTTypeWriter.AddActivatableAttribute(EntityHandle parentHandle, UInt32 version, String factoryInterface)
   at Generator.WinRTTypeWriter.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Generator.WinRTTypeWriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Generator.SourceGenerator.Execute(GeneratorExecutionContext context)
```

Figuring I probably messed something up with my project I decided to go to the source and check out the AuthoringSample project. Unfortunately I'm getting a very similar output in the log.txt:

```
Generating assembly AuthoringSample version 1.0.0.0
attribute type found 
adding attribute type
System.NullReferenceException: Object reference not set to an instance of an object.
   at Generator.WinRTTypeWriter.AddType(INamedTypeSymbol type)
   at Generator.WinRTTypeWriter.AddCustomAttributes(String attributeTypeName, IList`1 primitiveTypes, IList`1 primitiveValues, EntityHandle parentHandle)
   at Generator.WinRTTypeWriter.AddGuidAttribute(EntityHandle parentHandle, String name)
   at Generator.WinRTTypeWriter.VisitDelegateDeclaration(DelegateDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Generator.WinRTTypeWriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Generator.SourceGenerator.Execute(GeneratorExecutionContext context)
```

Figuring I should rule out any type compatibility issues, my new project only contains a single type definition:

```
namespace ICD.Profound.AppSwitcher.WinRT.Component
{
	public sealed class TestClass
	{
		public string TestProperty { get { return "Hello world!"; } }
	}
}
```

Am I doing something dumb here?

**Comment by vesuvian** [comment]
I've added a simple null check to WinRTTypeWriter in the AddCustomAttributes method:

```
            var attributeType = Model.Compilation.GetTypeByMetadataName(attributeTypeName);
            if (attributeType == null)
	            return;
```

The log looks much happier:

```
Generating assembly AuthoringSample version 1.0.0.0
method: GetPoint
method: GetCustomWWW
method: GetBasicStruct
method: GetSumOfInts
method: GetComplexStruct
method: GetX
generic type
Mapping known type: System.Nullable
Mapping System.Nullable to Windows.Foundation.IReference`1 from Windows.Foundation.FoundationContract
method: SetBasicEnum
method: GetBasicEnum
method: SetFlagsEnum
method: GetFlagsEnum
method: ReturnParameter
method: PrivateFunction
defining event ComplexDelegateEvent
add method from symbol: GetPoint
add method from symbol: GetCustomWWW
add method from symbol: GetBasicStruct
add method from symbol: GetSumOfInts
add method from symbol: GetComplexStruct
add method from symbol: GetX
generic type
Mapping known type: System.Nullable
Mapping System.Nullable to Windows.Foundation.IReference`1 from Windows.Foundation.FoundationContract
add method from symbol: SetBasicEnum
add method from symbol: GetBasicEnum
add method from symbol: SetFlagsEnum
add method from symbol: GetFlagsEnum
add method from symbol: ReturnParameter
member for synthesized interface not recognized: NamedType BasicClass
writing generated interface Default
generic type
Mapping known type: System.Nullable
Mapping System.Nullable to Windows.Foundation.IReference`1 from Windows.Foundation.FoundationContract
generic type
Mapping known type: System.Nullable
Mapping System.Nullable to Windows.Foundation.IReference`1 from Windows.Foundation.FoundationContract
defining property Name
parent: CustomWWW
defining property Value
parent: CustomWWW
member for synthesized interface not recognized: NamedType CustomWWW
writing generated interface Default
method: GetDouble
method: GetDouble
Overloading GetDouble with GetDouble2
method: FireComplexDelegate
method: GetThree
method: TestClass_BasicDelegateEvent
method: GetDefaultFactor
method: GetDefaultNumber
method: FireBasicDelegate
method: FireBasicDelegate2
method: GetFactor
method: GetNumber
method: GetNumber
method: GetNumberWithDelta
method: GetDouble
method: GetDouble
method: FireComplexDelegate
method: GetThree
add method from symbol: GetDefaultFactor
add method from symbol: GetDefaultNumber
writing generated interface Static
adding factory method: .ctor
writing generated interface Factory
defining event BasicDelegateEvent
defining event BasicDelegateEvent2
defining property Factor
parent: TestClass
defining property DelegateValue
parent: TestClass
member for synthesized interface not recognized: Method .ctor
member for synthesized interface not recognized: Method .ctor
add method from symbol: FireBasicDelegate
add method from symbol: FireBasicDelegate2
add method from symbol: GetFactor
add method from symbol: GetNumber
add method from symbol: GetNumber
add method from symbol: GetNumberWithDelta
writing generated interface Default
Overloading GetNumber with GetNumber2
attribute: System.FlagsAttribute
attribute type: System.FlagsAttribute
attribute constructor: System.FlagsAttribute.FlagsAttribute()
atttribute # constructor arguments: 0
atttribute # named arguments: 0
adding method reference: .ctor
Mapping known type: System.FlagsAttribute
Mapping System.FlagsAttribute to System.FlagsAttribute from mscorlib
found # constructors: 1
Writing D:\Downloads\CsWinRT-master\src\Authoring\AuthoringSample\Generated Files\net5.0\AuthoringSample.winmd
Created temp folder: C:\Users\Chris\AppData\Local\Temp\CsWinRT\0kl3y32g.fva
Running D:\Downloads\CsWinRT-master\src\_build\x64\Debug\cswinrt\bin\cswinrt.exe -component -input "D:\Downloads\CsWinRT-master\src\Authoring\AuthoringSample\Generated Files\net5.0\AuthoringSample.winmd" -input 10.0.18362.0 -include AuthoringSample -output "C:\Users\Chris\AppData\Local\Temp\CsWinRT\0kl3y32g.fva" -verbose
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.MachineLearningContract\2.0.0.0\Windows.AI.MachineLearning.MachineLearningContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract\2.0.0.0\Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\2.0.0.0\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsPhoneContract\5.0.0.0\Windows.ApplicationModel.Calls.CallsPhoneContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsVoipContract\4.0.0.0\Windows.ApplicationModel.Calls.CallsVoipContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.SocialInfo.SocialInfoContract\2.0.0.0\Windows.ApplicationModel.SocialInfo.SocialInfoContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.StartupTaskContract\3.0.0.0\Windows.ApplicationModel.StartupTaskContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0\Windows.Devices.Custom.CustomDeviceContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.DevicesLowLevelContract\3.0.0.0\Windows.Devices.DevicesLowLevelContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.PrintersContract\1.0.0.0\Windows.Devices.Printers.PrintersContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\3.0.0.0\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardEmulatorContract\6.0.0.0\Windows.Devices.SmartCards.SmartCardEmulatorContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\Windows.Foundation.FoundationContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.UniversalApiContract\8.0.0.0\Windows.Foundation.UniversalApiContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.XboxLive.StorageApiContract\1.0.0.0\Windows.Gaming.XboxLive.StorageApiContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Graphics.Printing3D.Printing3DContract\4.0.0.0\Windows.Graphics.Printing3D.Printing3DContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0\Windows.Networking.Connectivity.WwanContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Sockets.ControlChannelTriggerContract\3.0.0.0\Windows.Networking.Sockets.ControlChannelTriggerContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.GuidanceContract\3.0.0.0\Windows.Services.Maps.GuidanceContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.LocalSearchContract\4.0.0.0\Windows.Services.Maps.LocalSearchContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Store.StoreContract\4.0.0.0\Windows.Services.Store.StoreContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.TargetedContent.TargetedContentContract\1.0.0.0\Windows.Services.TargetedContent.TargetedContentContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0\Windows.System.Profile.ProfileHardwareTokenContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileSharedModeContract\2.0.0.0\Windows.System.Profile.ProfileSharedModeContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\3.0.0.0\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.SystemManagementContract\6.0.0.0\Windows.System.SystemManagementContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0\Windows.UI.ViewManagement.ViewManagementViewScalingContract.winmd
input: C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Core.Direct.XamlDirectContract\2.0.0.0\Windows.UI.Xaml.Core.Direct.XamlDirectContract.winmd
input: D:\Downloads\CsWinRT-master\src\Authoring\AuthoringSample\Generated Files\net5.0\AuthoringSample.winmd
output: C:\Users\Chris\AppData\Local\Temp\CsWinRT\0kl3y32g.fva
error: 'Type 'AuthoringSample.BasicClass' does not have a default interface' when processing AuthoringSample.BasicClass
 error: Type 'AuthoringSample.BasicClass' does not have a default interface


Done
```

And I have a resulting AuthoringSample.winmd in the Generated Files directory.

**Comment by manodasanW** [comment]
@vesuvian thanks for trying out the authoring support.  Can you try changing your TargetFramework to net5.0-windows10.0.<windows_sdk_ver>.0 (i.e. net5.0-windows10.0.19041.0) and see if you still hit the issue.

The Windows API version specific TFM is what brings in the Windows projection and the line that is erroring is trying to look for a type that would exist there.  The AuthoringSample itself should have worked as it refers to a test Windows projection that we build as part of this repo, so it is strange that also failed.

**Comment by manodasanW** [comment]
Closing issue, please re-open if suggested change doesn't resolve issue.
