### ISSUE TITLE
GetAppListEntriesAsync raises STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by trympet** [microsoft/CsWinRT#679]
**Describe the bug**
Invoking `Package.Current.GetAppListEntriesAsync()` results in STATUS_ACCESS_VIOLATION (0xC0000005).

My knowledge with native debugging is very limited. I have a minidump which can be sent upon request. My email is available form my GitHub profile.

**To Reproduce**

1. Create a WPF app and packaging project.
2. Invoke and await `Package.Current.GetAppListEntriesAsync()`
3. Package and install app
4. Run app

**Expected behavior**
No error is raised.

**Version Info**
TFM: net5.0-windows10.0.17763.0
CLR: 5.0.120.57516
OS: 10.0.21292.1000
SDK: 5.0.101

**Additional context**
FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_coreclr.dll!EEPolicy::HandleFatalError
FAULTING_SOURCE_FILE:  F:\workspace\_work\1\s\src\coreclr\src\vm\eepolicy.cpp
FAULTING_SOURCE_LINE_NUMBER:  747

Trace:
```
Frame	Image	Function	Offset
0	coreclr.dll	ProcessCLRException	0x00000000000F1A19	
1	coreclr.dll	EEPolicy::HandleFatalError	0x000000000000007F	
2	coreclr.dll	ProcessCLRException	0x00000000000F1A38	
3	coreclr.dll	EECodeInfo::Init	0x0000000000000059	
4	coreclr.dll	EECodeInfo::GetFunctionEntry	0x000000000000002C	
5	coreclr.dll	GetRuntimeFunctionCallback	0x0000000000000045	
6	coreclr.dll	GetRuntimeFunctionCallback	0x0000000000000000	
7	ntdll.dll	RtlpLookupDynamicFunctionEntry	0x0000000000000108	
8	ntdll.dll	RtlpExecuteHandlerForException	0x000000000000000F	
9	ntdll.dll	RtlDispatchException	0x0000000000000219	
10	sechost.dll	__midl_frag49	0x0000000000000000	
11	rpcrt4.dll	Ndr64SimpleStructUnmarshall	0x000000000000021F	
12	coreclr.dll	ExecutionManager::IsManagedCodeWithLock	0x000000000000002C	
13	coreclr.dll	ShouldHandleManagedFault	0x00000000000C1F8A	
14	coreclr.dll	CLRVectoredExceptionHandlerPhase2	0x00000000000000C7	
15	ntdll.dll	RtlpProtectHeap	0x0000000000000061	
16	coreclr.dll	CLRVectoredExceptionHandler	0x000000000000008B	
17	ntdll.dll	RtlProtectHeap	0x00000000000000BD	
18	ntdll.dll	LdrSystemDllInitBlock	0x0000000000000031	
19	ntdll.dll	RtlpCallVectoredHandlers	0x0000000000000298	
20	ntdll.dll	LdrpVectorHandlerList	0x0000000000000000	
21	ntdll.dll	LdrpVectorHandlerList	0x0000000000000008	
22	ntdll.dll	RtlGetExtendedContextLength2	0x0000000000000022	
23	ntdll.dll	RtlDispatchException	0x00000000000000EC	
24	rpcrt4.dll	EtwEventSubjectFilter	0x0000000000000000	
25	combase.dll	ObjectStublessEnd	0x0000000000000000	
26	rpcrt4.dll	__PchSym_ _PERF_ 	0x0000000000000000	
27	rpcrt4.dll	__PchSym_ _PERF_ 	0x0000000000000000	
28	rpcrt4.dll	__PchSym_ _PERF_ 	0x0000000000000000	
29	combase.dll	__PchSym_ _PERF_ 	0x0000000000000000	
30	combase.dll	__PchSym_ _PERF_ 	0x0000000000000000	
31	combase.dll	__PchSym_ _PERF_ 	0x0000000000000000	
32	combase.dll	__ImageBase	0x0000000000000000	
33	combase.dll	__PchSym_ _PERF_ 	0x0000000000000000	
34	ntdll.dll	KiUserExceptionDispatch	0x000000000000002E	
35	rpcrt4.dll	__ImageBase	0x0000000000000000	
36	rpcrt4.dll	Ndr64ConformantStringBufferSize	0x0000000000000063	
37	combase.dll	__midl_frag59	0x0000000000000000	
38	rpcrt4.dll	Ndr64TopLevelPointerBufferSize	0x0000000000000000	
39	rpcrt4.dll	Ndr64ComplexStructBufferSize	0x0000000000000000	
40	rpcrt4.dll	Ndr64ConformantArrayBufferSize	0x0000000000000000	
41	rpcrt4.dll	BCACHE::Free	0x000000000000009D	
42	rpcrt4.dll	RestoreOldThreadToken	0x000000000000004A	
43	rpcrt4.dll	LRPC_CASSOCIATION::CompleteBind	0x000000000000012D	
44	ntdll.dll	RtlEqualSid	0x0000000000000025	
45	rpcrt4.dll	LRPC_CASSOCIATION::Bind	0x00000000000006CE	
46	combase.dll	IRuntimeBroker_SyntaxInfo	0x0000000000000000	
47	rpcrt4.dll	LRPC_BINDING_HANDLE::NegotiateTransferSyntax	0x00000000000005AF	
48	rpcrt4.dll	Ndr64ConformantStringBufferSize	0x0000000000000073	
49	ntdll.dll	RtlpHpLfhSlotAllocate	0x0000000000000102	
50	KERNELBASE.dll	BaseSetLastNTError	0x000000000000001D	
51	KERNELBASE.dll	OpenThreadToken	0x000000000000001B	
52	combase.dll	CChannelHandle::AdjustToken	0x000000000000005C	
53	combase.dll	ObjectLibrary::Details::InstrumentedField_unsigned long,CMessageCall,&CMessageCall::GetFieldOffset__iFlags,{CMessageCall::OnFieldChanged__iFlags,0,0},1_::SetValue	0x0000000000000036	
54	combase.dll	StandardComClientCall::NegotiateSyntax	0x0000000000000098	
55	combase.dll	CClientChannel::NegotiateSyntax	0x000000000000008E	
56	combase.dll	CClientChannel::QueryInterface	0x00000000000001D9	
57	rpcrt4.dll	Ndr64pSizing	0x0000000000000118	
58	combase.dll	NdrExtInitializeCallObject	0x0000000000000087	
59	combase.dll	NdrOleExportForwardTable	0x0000000000000121	
60	rpcrt4.dll	NdrpClientCall3	0x000000000000032C	
61	rpcrt4.dll	CaptureModifiedIdEx	0x0000000000000082	
62	combase.dll	NdrOleExtensionTable	0x0000000000000000	
63	rpcrt4.dll	LRPC_BASE_BINDING_HANDLE::SetAuthInformation	0x0000000000000385	
64	combase.dll	NdrOleAllocate	0x0000000000000000	
65	combase.dll	NdrOleFree	0x0000000000000000	
66	combase.dll	Object_StubDesc	0x0000000000000000	
67	rpcrt4.dll	Ndr64ClientInitializeContext	0x0000000000000088	
68	combase.dll	ObjectStublessClient	0x000000000000013B	
69	combase.dll	__midl_frag57	0x0000000000000000	
70	combase.dll	__midl_frag57	0x0000000000000018	
71	combase.dll	iinspectablederived__MIDL_ProcFormatString	0x000000000000019A	
72	combase.dll	IRuntimeBroker_SyntaxInfo	0x0000000000000050	
73	rpcrt4.dll	Ndr64pClientInit	0x0000000000000000	
74	rpcrt4.dll	Ndr64pSizing	0x0000000000000000	
75	rpcrt4.dll	Ndr64pClientMarshal	0x0000000000000000	
76	rpcrt4.dll	Ndr64pClientUnMarshal	0x0000000000000000	
77	rpcrt4.dll	Ndr64pDcomClientExceptionHandling	0x0000000000000000	
78	rpcrt4.dll	Ndr64pClientFinally	0x0000000000000000	
79	combase.dll	IRuntimeBroker_ProxyInfo	0x0000000000000000	
80	ntdll.dll	RtlpAllocateHeapInternal	0x0000000000000400	
81	combase.dll	CStdIdentity::CInternalUnk::QueryMultipleInterfacesLocal	0x000000000000034F	
82	ntdll.dll	RtlpHpAllocWithExceptionProtection	0x0000000000000015	
83	undefined	utl::_Tree_RuntimeBrokerCacheKey,utl::pair_RuntimeBrokerCacheKey const ,Microsoft::WRL::ComPtr_IRuntimeBroker_ _,RuntimeBrokerCacheKeyCompareFunctor,utl::allocator_utl::pair_RuntimeBrokerCacheKey const ,Microsoft::WRL::ComPtr_IRuntimeBroker_ _ _,0_::empla	0x000000000000007F	
84	combase.dll	Microsoft::WRL::ComPtr_Windows::Foundation::Collections::IMapView_unsigned int,HSTRING__ *_ _::InternalAddRef	0x0000000000000019	
85	combase.dll	`string'	0x0000000000000000	
86	combase.dll	ObjectStubless	0x0000000000000042	
87	combase.dll	RuntimeBrokerActivation	0x00000000000000B1	
88	combase.dll	DetermineActivationActionForRequest	0x0000000000000094	
89	combase.dll	_RoGetActivationFactory	0x0000000000000653	
90	combase.dll	s_catalogObject	0x0000000000000028	
91	ntdll.dll	RtlpFreeHeap	0x000000000000070E	
92	coreclr.dll	PrepareCodeConfig::`vftable'	0x0000000000000000	
93	ntdll.dll	RtlFreeHeap	0x000000000000006C	
94	coreclr.dll	CrstBase::Destroy	0x0000000000000074	
95	coreclr.dll	operator delete[]	0x000000000000001B	
96	coreclr.dll	MethodDesc::FindOrCreateAssociatedMethodDesc	0x00000000000020A1	
97	coreclr.dll	CrstBase::Leave	0x0000000000000013	
98	coreclr.dll	ListLockEntryBase_void *_::Release	0x0000000000000063	
99	coreclr.dll	MethodTable::DoRunClassInitThrowing	0x00000000000003DC	
100	coreclr.dll	ReflectionInvocation::GetGUID	0x00000000000001F7	
101	coreclr.dll	ReflectionInvocation::GetGUID	0x0000000000000000	
102	coreclr.dll	HelperMethodFrame_1OBJ::`vftable'	0x0000000000000000	
103	coreclr.dll	InlinedCallFrame::`vftable'	0x0000000000000000	
104	coreclr.dll	MethodDescCallSite::CallTargetWorker	0x0000000000000268	
105	coreclr.dll	TryCallMethodWorker	0x0000000000000022	
106	coreclr.dll	SigPointer::PeekElemTypeNormalized	0x0000000000000025	
107	coreclr.dll	MetaSig::Init	0x00000000000000FE	
108	coreclr.dll	TryCallMethod	0x00000000000000E9	
109	coreclr.dll	MetaSig::GetReturnTypeNormalized	0x0000000000000026	
110	coreclr.dll	MethodDesc::GetCallTarget	0x0000000000000014	
111	coreclr.dll	ArgIteratorTemplate_ArgIteratorBase_::ForceSigWalk	0x00000000000000EF	
112	coreclr.dll	RuntimeTypeHandle::CreateInstance	0x000000000000026D	
113	coreclr.dll	LoaderAllocator::AllocateHandle	0x00000000000000F6	
114	Microsoft.Windows.SDK.NET.dll	undefined	0x0000000001644B11	
115	Microsoft.Windows.SDK.NET.dll	undefined	0x0000000001644B10	
116	coreclr.dll	g_pSystemDomainMemory	0x0000000000000508	
117	coreclr.dll	TypeHandle::GetManagedClassObject	0x0000000000000112	
118	coreclr.dll	RuntimeTypeHandle::CreateInstance	0x0000000000000000	
119	coreclr.dll	RuntimeTypeHandle::CreateInstance	0x00000000000000DA	
120	System.Private.CoreLib.dll	undefined	0x00000000004242CE	
121	coreclr.dll	`string'	0x0000000000000000	
122	undefined	undefined	0x0000000000000000	
123	undefined	undefined	0x0000000000000000	
124	undefined	undefined	0x0000000000000000	
125	undefined	undefined	0x0000000000000000	
126	undefined	[thunk]:Windows::Internal::AsyncOperation_Windows::Foundation::IAsyncOperation_bool_,Windows::Foundation::IAsyncOperationCompletedHandler_bool_,Windows::Internal::CBasicResult_unsigned char,0_,Windows::Internal::ComTaskPoolHandler,Windows::Internal::INilD	0x0000000000000000	
127	undefined	undefined	0x0000000000000000	
128	undefined	[thunk]:Windows::Internal::AsyncOperation_Windows::Foundation::IAsyncOperation_bool_,Windows::Foundation::IAsyncOperationCompletedHandler_bool_,Windows::Internal::CBasicResult_unsigned char,0_,Windows::Internal::ComTaskPoolHandler,Windows::Internal::INilD	0x0000000000000000	
129	undefined	undefined	0x0000000000000000	
130	System.Private.CoreLib.dll	undefined	0x0000000000522AE9	
131	System.Private.CoreLib.dll	undefined	0x0000000000530DF5	
132	coreclr.dll	CallDescrWorkerReflectionWrapper	0x000000000000001A	
133	coreclr.dll	ArgIteratorTemplate_ArgIteratorBaseForMethodInvoke_::GetNextOffset	0x000000000000008E	
134	coreclr.dll	RuntimeMethodHandle::InvokeMethod	0x00000000000003EF	
135	coreclr.dll	ArgIteratorForMethodInvoke::ArgIteratorForMethodInvoke	0x0000000000000052	
136	coreclr.dll	CallDescrWorkerInternal	0x0000000000000083	
137	coreclr.dll	RuntimeMethodHandle::InvokeMethod	0x0000000000000174	
138	coreclr.dll	MetaSig::NextArg	0x00000000000000DC	
139	coreclr.dll	DebuggerU2MCatchHandlerFrame::`vftable'	0x0000000000000000	
140	coreclr.dll	IsInstanceOfTypeHelper	0x00000000000000F3	
141	coreclr.dll	HelperMethodFrame_2OBJ::`vftable'	0x0000000000000000	
142	coreclr.dll	GetRuntimeTypeHelper	0x000000000000006D	
143	coreclr.dll	RuntimeTypeHandle::IsInstanceOfType	0x0000000000000000	
144	coreclr.dll	HelperMethodFrame_PROTECTOBJ::`vftable'	0x0000000000000000	
145	coreclr.dll	RuntimeMethodHandle::InvokeMethod	0x0000000000000000	
146	coreclr.dll	RuntimeMethodHandle::InvokeMethod	0x00000000000000BE	
147	SHCore.dll	WorkThreadManager::s_taskFloodingList	0x0000000000000000	
148	System.Private.CoreLib.dll	undefined	0x00000000003F1397	
149	System.Private.CoreLib.dll	undefined	0x00000000003F23DE	
150	undefined	Windows::Internal::AsyncBaseFTM_Windows::Foundation::IAsyncOperationCompletedHandler_Windows::Foundation::Collections::IVectorView_Windows::ApplicationModel::Core::AppListEntry *_ *_,1,Microsoft::WRL::AsyncOptions_-1,0,&GUID_CAUSALITY_WINDOWS_PLATFORM_ID,	0x00000000000001A0	
151	SHCore.dll	SHTaskPoolAllowThreadReuse	0x000000000000000A	
152	undefined	undefined	0x0000000000000092	
153	undefined	undefined	0x000000000000010A	
154	ntdll.dll	LdrUnloadDll	0x0000000000000051	
155	ntdll.dll	RtlSetLastWin32Error	0x0000000000000040	
156	user32.dll	RealMsgWaitForMultipleObjectsEx	0x000000000000001D	
157	undefined	undefined	0x0000000000000069	
158	SHCore.dll	WorkThreadManager::CThread::ThreadProc	0x0000000000000229	
159	SHCore.dll	WorkThreadManager::CThread::s_ExecuteThreadProc	0x0000000000000018	
160	SHCore.dll	_lambda_9844335fc14345151eefcc3593dd6895_::_lambda_invoker_cdecl_	0x0000000000000011	
161	kernel32.dll	BaseThreadInitThunk	0x0000000000000014	
162	ntdll.dll	RtlUserThreadStart	0x0000000000000021	
```

**Comment by manodasanW** [comment]
@trympet I tried to repro this, but don't seem to be hitting a crash with your repro steps.  Is there anything else you had to do such as maybe with your configuration of the packaging project?

**Comment by trympet** [comment]
Hi. I have been unable to reproduce the issue consistently. In the managed debugger, I have also observed COMExceptions with hresult 0x80070490 (Element not found) in the managed debugger. I don't know if this is related.

I am encountering similar issues with the `TileUpdater.Update()` method also throwing 0xC0000005 Access violation. Would you like a memory dump?

Trace:
```
wpnapps.dll	_lambda_2619649b95572be61c6cb2e74b069ec2_::_lambda_invoker_cdecl_	0x0000000000000000
wpnapps.dll	wil::details::static_lazy_WpnApiTelemetry_::get	0x0000000000000032
wpnapps.dll	wil::TraceLoggingProvider::IsEnabled_	0x0000000000000015
wpnapps.dll	WpnApiTelemetry::Update_Windows::Internal::NativeString_Windows::Internal::CoTaskMemPolicy_unsigned short_ _ &,long &_	0x0000000000000036
wpnapps.dll	Windows::UI::Notifications::TileUpdater::Update	0x000000000000003C
wpnapps.dll	Windows::UI::Notifications::TileUpdater::Update	0x0000000000000000
coreclr.dll	JIT_GetSharedGCThreadStaticBase	0x0000000000000070
KERNELBASE.dll	QueueUserAPC	0x0000000000000090
coreclr.dll	ThreadpoolMgr::ChangeTimerQueueTimer	0x0000000000000080
coreclr.dll	InlinedCallFrame::`vftable'	0x0000000000000000
coreclr.dll	CallDescrWorkerInternal	0x0000000000000083
coreclr.dll	MethodDescCallSite::CallTargetWorker	0x0000000000000268
coreclr.dll	ThreadpoolMgr::FlushQueueOfTimerInfos	0x0000000000000060
coreclr.dll	AppDomainTimerCallback_Worker
```

**Comment by AdamBraden** [comment]
@trympet - can you share a pointer to a repo that demonstrates this bug? We have not been able to recreate.

**Comment by AdamBraden** [comment]
@trympet - if you create a memory dump, you can create an issue in Feedback Hub and attach the dump. Then share the link here.

**Comment by trympet** [comment]
Hello @AdamBraden, sorry for the slow reply.

I created [an issue in Feedback Hub](https://aka.ms/AAb9thz) with some dumps attached.

I have attempted to replicate the bug, but have been unable to do so in my test env. 

However, I am pretty sure this issue is related to the live tile updater; @andrewleader. The entire API is throwing errors left and right. They are all thrown while invoked from an async context. This might be due to the way the tile updater was being instantiated. See example below.

```csharp
TileUpdater tileUpdater = null;
while (tileUpdater is null)
{
    try
    {
        tileUpdater = TileUpdateManager.CreateTileUpdaterForApplication();
        tileUpdater.EnableNotificationQueue(false);
    }
    catch (COMException e) when (e.HResult == unchecked((int)RPC_E_WRONG_THREAD))
    {
        // Attempt to create tile updater again and again until new (internal) singleton 
        // is dispatched.
    }
}
```

Some of the errors I have observed from the TileUpdater API include:
## Error 1
Exception message: `The notification platform is unavailable. (0x803E0105)`
```csharp
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.Notifications.ITileUpdater.global::Windows.UI.Notifications.ITileUpdater.Update(TileNotification notification)
   at TileNotification.TileManager.PublishTile(IEnumerable`1 notifications, CancellationToken cancellationToken)
```

## Error 2
Exception message: `Insertion failed because database is full (0x87AF000D)`
```csharp
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.Notifications.ITileUpdater.global::Windows.UI.Notifications.ITileUpdater.EnableNotificationQueue(Boolean enable)
   at TileNotification.TileManager.PublishTile(IEnumerable`1 notifications, CancellationToken cancellationToken)
```

## Error 3
This error had 2 nested exceptions.


Exception type: `TargetInvocationException`
Exception message: `Exception has been thrown by the target of an invocation`
```csharp
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Windows.UI.Notifications.TileNotification.<>c__DisplayClass8_0.<.ctor>b__0()
   at Windows.UI.Notifications.TileNotification..ctor(XmlDocument content)
   at TileNotification.Notification..ctor(ILiveTileData data)
   at TileNotification.TileManager.PublishTile(IEnumerable`1 notifications, CancellationToken cancellationToken)
```

Inner exception type: `TargetInvocationException`
Inner exception message: `Exception has been thrown by the target of an invocation`
Inner exception HResult: `-2146232828`
```csharp
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Windows.UI.Notifications.TileNotification._ITileNotificationFactory..ctor()
```

Nested inner exception type: `ArgumentException`
Nested inner exception message: `Value does not fall within the expected range`
Nested inner exception HResult: `-2147024809`
```csharp
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
```

## Error 4
```csharp
at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
at ABI.Windows.Foundation.Metadata.IApiInformationStatics.global::Windows.Foundation.Metadata.IApiInformationStatics.IsTypePresent(String typeName)
at TileNotification.TileManager.PublishTile(IEnumerable`1 notifications, CancellationToken cancellationToken)
```
HResult: `-2147024809`

## Error 5
```csharp
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at Windows.UI.Notifications.TileNotification._ITileNotificationFactory.CreateTileNotification(XmlDocument content)
   at Windows.UI.Notifications.TileNotification.<>c__DisplayClass8_0.<.ctor>b__0()
   at Windows.UI.Notifications.TileNotification..ctor(XmlDocument content)
   at TileNotification.Notification..ctor(ILiveTileData data)
   at TileNotification.TileManager.PublishTile(IEnumerable`1 notifications, CancellationToken cancellationToken)
```
HResult: `-2147417842`

---

There are more errors, but hopefully this is enough to go by. I also have access to minidumps, courtesy of WER.

**Comment by andrewleader** [comment]
@trympet if you're getting tile errors like DB full, maybe your PC or VM you're testing on is corrupted? Have you tried the same code on another computer?

**Comment by trympet** [comment]
@andrewleader none of these stacktraces above (or the dumps in Feedback Hub) are from my machine. I should have prefaced this by stating that the errors are from a Microsoft Store application with a significant user base.

I have not been able to recreate the issue on my computer. However, several thousands users, running various builds of Windows, are encountering the same issues. I have access to dumps and minidumps from Windows Error Reporting via Partner Center, and managed stacktraces from Elasticsearch.

Below is a screenshot illustrating the impact of the issue:

![image](https://user-images.githubusercontent.com/23460729/108907800-dd60b400-7622-11eb-9c72-6b89bb6e06b7.png)

**Comment by trympet** [comment]
@andrewleader If you'd like, you can send me a message on the email address on my Github profile, and I'll send over some managed and unmanaged dumps captured by WER, along with symbols.

**Comment by trympet** [comment]
I should also add that the `Database is full` errors began cropping up after explicitly assigning a value to the `TileNotification.ExpirationTime`. In prior versions, when the property was not set, `Database is full` was not among the exceptions that were thrown.

**Comment by andrewleader** [comment]
Hmm interesting! I'll reach out to your email. Thank you so much for sharing all of this info, super helpful! Btw, if this tile notifications issue is the extent of your issue, you can close this issue (since it's not a CsWinRT bug but instead a Windows Platform bug and we track those internally). Look for an email from me in ~10 mins!
