### ISSUE TITLE
DisplayRequest RequestActive fails with exception "0x80040200"

### ISSUE THREAD

**Issue by craigomatic** [microsoft/CsWinRT#962]
**Describe the bug**

Calling ```DisplayRequest.RequestActive``` fails with a COM exception 0x80040200

**Steps to reproduce the bug**

1. Create a new default WinUI app in Visual Studio 2019
2. Change the myButton_Click handler in MainWindow.xaml.cs to 
```
try
{
    var request = new DisplayRequest();
    request.RequestActive();

    myButton.Content = "DisplayRequest successful";
}
catch (Exception ex)
{
     myButton.Content = $"DisplayRequest failed: {ex.ToString()}";
}
```
The button content will change to display the exception message.

**Expected behavior**

The DisplayRequest should either give a more descriptive error message that tells the developer what they have forgotten/the reason why it's not working, or, this should just work like it does in a classic UWP app.

**Screenshots**

n/a

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion v0.8.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
Windows 11 Build 22000.120 | Yes
Vanilla Windows 10 (sorry I will get the version and update) | Yes

**Additional context**

**Comment by Scottj1s** [comment]
Based on [craigomatic's comment yesterday](https://github.com/microsoft/CsWinRT/issues/962#issuecomment-897929713) and repro in UWP, this doesn't sound like a CsWinRT issue.

**Comment by AdamBraden** [comment]
Agree that is confusing, but I think are best positioned to investigate and then redirect where needed.

**Comment by angelazhangmsft** [comment]
From my investigation, this code worked in .NET Native (C# UWP app), but causes a COMException in both .NET Core 3.1 (with the contracts package) and .NET 5 (with the TFM).

System.Runtime.InteropServices.COMException: 'Activating a single-threaded class from MTA is not supported (0x8000001D)'

**Comment by neilt6** [comment]
I'm experiencing this issue with multiple WPF apps built using .NET 5 and distributed via the Microsoft Store. In my case, `DisplayRequest` throws a `COMException (0x80040200)` on Windows 11 _(build 22000.184)_, but works fine on Windows 10 _(up to and including build 19043.1165)_.

I'll link one of them here as a way of reproducing the bug:
### Microsoft Store Link
[DAVID Live](https://www.microsoft.com/en-ca/p/david-live/9nb77vxh941k)
### Step 1: Click _Start Live Session_
![Screenshot 2021-09-13 130744](https://user-images.githubusercontent.com/2797902/133143507-9775f63c-65fd-49f5-a090-00cdd4b6ebdc.png)
### Step 2: Click _Start_
![Screenshot 2021-09-13 130805](https://user-images.githubusercontent.com/2797902/133143534-80a66e96-081d-47c3-ad1d-386e7ce35e45.png)
### Result
```
Application: DAVID Live.exe
CoreCLR Version: 5.0.821.31504
.NET Version: 5.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80040200): 0x80040200
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.System.Display.IDisplayRequest.global::Windows.System.Display.IDisplayRequest.RequestActive()
   at Windows.System.Display.DisplayRequest.RequestActive()
   at MindAliveInc.DavidLive.Live.ViewModels.LiveViewModel.OnActivateAsync(CancellationToken cancellationToken)
   at Caliburn.Micro.Screen.Caliburn.Micro.IActivate.ActivateAsync(CancellationToken cancellationToken)
   at Caliburn.Micro.ConductorBaseWithActiveItem`1.ChangeActiveItemAsync(T newItem, Boolean closePrevious, CancellationToken cancellationToken)
   at Caliburn.Micro.Conductor`1.ActivateItemAsync(T item, CancellationToken cancellationToken)
   at MindAliveInc.Gui.Navigation.NavigationConductor`1.PerformNavigationAsync(T targetViewModel, Object extraData, NavigationMode navigationMode, CancellationToken cancellationToken)
   at MindAliveInc.Gui.Navigation.NavigationConductor`1.NavigateToViewModelAsync(Type viewModel, Object extraData)
   at MindAliveInc.DavidLive.Home.ViewModels.HomeViewModel.StartLiveSessionAsync()
   at MindAliveInc.Gui.CaliburnUtilities.<>c__DisplayClass2_0.<<EnableActionReentrancyProtection>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at MindAliveInc.DavidLive.App.Main()
```
