### ISSUE TITLE
TypeInitializationException in PointCollection regression in 0.8.2

### ISSUE THREAD

**Issue by Marv51** [microsoft/CsWinRT#971]
**Describe the bug**
Crashing exception in PointCollection introduced in 0.8.2

**Steps to reproduce the bug**
```
var pc = new PointCollection();
```
Adding this line to an empty WinUI 3 desktop project results in an exception: 
`System.TypeInitializationException: The type initializer for '<SignatureCache>System.Collections.Generic.IList'1<Windows.Foundation.Point>' threw an exception.'`

With inner exception: 
`TypeLoadException: Could not load type 'ABI.Windows.Foundation.Point' from assembly 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'.`

Stack Trace 
```csharp
   at <GuidPatcherImplementationDetails>.<IIDData>System.Collections.Generic.IList`1<Windows.Foundation.Point>()
   at Microsoft.UI.Xaml.Media.PointCollection..ctor(IObjectReference objRef)
   at Microsoft.UI.Xaml.Media.PointCollection..ctor()
   at App12.MainWindow.myButton_Click(Object sender, RoutedEventArgs e) in C:\Users\Marvin\source\repos\App12\App12\MainWindow.xaml.cs:line 34
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(RoutedEventHandler invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```
**Version Info**

NuGet package version: 
WinUI 3 - Windows App SDK 0.8: 0.8.2
Was working in 0.8.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 (19043)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Clear regression, most likely CsWinRT related. Impact: Crash on launch, blocks us completely.

**Comment by Scottj1s** [comment]
Setting CsWinRTIIDOptimizerOptOut won't help here - the problem is in Microsoft.WinUI.dll (WinUI 3 projection assembly).  

The IIDOptimizer should be rewriting the type reference to ABI.Windows.Foundation.Point as coming from winrt.runtime.dll, not Microsoft.WinUI.dll

**Comment by Marv51** [comment]
@j0shuams Did you already have a chance to look at this? Are you able to reproduce the crash? 

This issue is very important for me as it makes the `Microsoft.UI.Xaml.Shapes.Polygon` class in WinUI unusable. Unfortunately, my app uses polygons in quite a few critical places.
